# Generated by Django 4.1.1 on 2023-01-23 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('sale', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingBillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=120, verbose_name='LastName')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('telephone', models.CharField(max_length=15, verbose_name='Phone')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('street_address1', models.CharField(max_length=255, verbose_name='Address1')),
                ('street_address2', models.CharField(max_length=255, verbose_name='Address2')),
                ('fax', models.IntegerField(verbose_name='fax')),
            ],
        ),
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('shippingbillinginfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card.shippingbillinginfo')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('password', models.CharField(max_length=25, verbose_name='password')),
            ],
            bases=('card.shippingbillinginfo',),
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('shippingbillinginfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card.shippingbillinginfo')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('postal_code', models.CharField(max_length=255, verbose_name='PostalCode')),
            ],
            bases=('card.shippingbillinginfo',),
        ),
    ]
